config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get 'articles/search' => 'articles#search'
  resources :articles do
    resources :comments

  end

  resources :user

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # t.string :name
  # t.string :email
  # t.string :mobile
  # t.string :password
  # t.datetime :register_at
  # t.string :register_ip

  # def initialize
  # end



  class << self
    def test(num)
      (1..num).each do |n|
        _name = SecureRandom.urlsafe_base64(3)
        _mobile = g_salt(11)
        _password = SecureRandom.urlsafe_base64(4)
        User.create(name: _name, mobile: _mobile, password: _password)
        p ('------------' + n.to_s)
      end
    end

    def g_salt(len)
      # chars = Array('a'..'z') + Array('A'..'Z') + Array(0..9)
      chars = Array(0..9)
      len.times.map { chars.sample }.join
    end
  end

  private

  def generate_token
    loop do
      self.token = SecureRandom.urlsafe_base64(6)
      break unless User.where(token: token).exists?
    end
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    if params[:ids]
      @articles = Article.find(params[:ids]).limit(10)
    else
      @articles = Article.all.limit(10)
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def search
    @articles = Article.where(['title like ?', "%#{params[:articles][:title]}%"])
    # if @articles.blank?
    #   redirect_to root_path
    # else
    #   redirect_to @articles
    # end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  include SessionsHelper

  def new
  end

  def create
    login = params[:sessions][:login]
    password = params[:sessions][:password]
    #User.find_by_login(login)是新增加的一个类方法，用来实现name或者email的登录
    user = User.find_by(name: login)
    #authenticate是has_secure_password引入的一个方法，用来判断user的密码与页面中传过来的密码是否一致
    # if user && user.authenticate(password)
    if user && user.password.to_s == password
      log_in(user) #SessionsHelper中的方法
      #判断是否要持续性的记住用户的登录状态
      # params[:sessions][:remeber_me] == "1" ? remeber(user) : forget(user)
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Invalid login or password."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in? #SessionsHelper中的方法
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  # user_index GET    /user(.:format)                                   user#index
  #                    POST   /user(.:format)                                   user#create
  # new_user GET    /user/new(.:format)                               user#new
  # edit_user GET    /user/:id/edit(.:format)                          user#edit
  # user GET    /user/:id(.:format)                               user#show
  # PATCH  /user/:id(.:format)                               user#update
  # PUT    /user/:id(.:format)                               user#update
  # DELETE /user/:id(.:format)                               user#destroy

  def index
    # @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit

  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def update

  end

  def destroy

  end

  def login
    @user = User.new
  end

  def login_to
    user = User.find_by(params[:user])
    session[:user_id] = user.id if user
    redirect_to user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
    @user = User.new
  end

  def create
    p '---------'
    p params
    user = User.find_by(name: params[:name], password: params[:password])
    session[:user_id] = user.id if user
  end

  def logout
    session[:user_id] = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def ckeditor(obj,field,config={})
    local_config = ""
    config.reject{|k,v| k == :text}.each do |key,value|
      _value=value
      #宽度可以设置百分比
      if key=='width'.to_sym
        if value.class.to_s=='String'&&value.index('%')
          percent = value.split('%')[0].to_i
          _value="document.body.scrollWidth *#{percent}*0.01"
        end
      end
      local_config+="CKEDITOR.config.#{key.to_s}=#{_value}; \n "
    end

    javascript_include_tag("/javascripts/ckeditor_full/ckeditor.js")+
        "<script>var ck_tag_name='#{obj}[#{field}]'</script>"+
        "<textarea cols='100' id='#{obj}[#{field}]' name='#{obj}[#{field}]' rows='20'></textarea>"+
        javascript_include_tag("/javascripts/ckeditor/ck_textarea.js")+
        javascript_include_tag("/javascripts/ckeditor/ck_head.js")+
        "<script>#{local_config}
      window.onload=function(){
        editor_obj = CKEDITOR.instances[ck_tag_name]
        editor_obj.setData('"+config[:text].to_s+"');
      }
    </script>"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #一旦账号密码正确，则成功登录，同时在session中记录session[:user_id]
  def log_in(user)
    session[:user_id] = user.id
  end
  #如果用户允许在本地保存登录信息，则保存cookies
  def remeber(user)
    #先把本次登录的remeber_token保存至数据库
    user.remeber
    #然后把remeber_token保存到cookies中，同时把user_id也保存在cookies中
    # cookies[:remeber_token] = { value: user.remeber_token, expires: 10.days.from_now.utc}
    # cookies.signed[:user_id] = { value: user.id, expires: 10.days.from_now.utc}
    cookies.permanent[:remeber_token] = user.remeber_token
    cookies.permanent.signed[:user_id] = user.id
  end
  #获取当前登录用户，如未登录，则为nil.@current_user这个实例变量是为了避免每次调用current_user方法都去查询一遍数据库的情况。
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def latest_articles
    @articles = Article.all.limit(3)
  end

  # def current_user
  #   #先判断session中是否为nil
  #   if (user_id = session[:user_id])
  #     @current_user ||= User.find_by(id: user_id)
  #     #再判断cookies中是否保存了登录信息
  #   else (user_id = cookies.signed[:user_id])
  #   user = User.find_by(id: user_id)
  #   #如果cookies中保存了，再用authenticated?这个方法判断cookies[:remeber_token]或者数据库中的remeber_digest是否一致。
  #   if user && user.authenticated?(cookies[:remeber_token])
  #     log_in(user)
  #     @current_user = user
  #   end
  #   end
  # end
  #用来判断用户是否登录的方法
  def logged_in?
    !current_user.nil?
  end
  #用来清空持久性登录信息
  def forget(user)
    # user.forget #将user.remeber_digest重置为nil
    #删除cookies中的登录信息
    cookies.delete(:user_id)
    # cookies.delete(:remeber_token)
  end
  #退出，同时删除session中的信息
  def log_out
    p '-----------------'
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
      <% if @article.errors.any? %>
          <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
          <% end %>
      <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
     
      <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
     
      <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/search.html.erb
<!--< %= render 'welcome/search' %>-->
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<div id="main">
  <div class="list">
    <table>
      <tr>
        <th>Title</th>
        <th>Text</th>
        <th colspan="2"></th>
      </tr>
      <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article_path(article),
                            method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/articles/show.html.erb
<style>
  div {
    display: block;
  }

  div#local {
    width: 188px;
    border: 1px black solid;
    padding: 10px 3px 0 3px;
    margin: 3px 3px 0 0;
    background-color: #fafafa;
    overflow: hidden;
    float: left;
  }

  #blog_owner {
    text-align: center;
    padding: 0 13px;
  }


  #blog_actions {
    margin-bottom: 20px;
  }

  ul {
    margin: 0 0 1.5em 0;
    padding: 0;
  }

  ul, menu, dir {
    display: block;
    list-style-type: disc;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 40px;
  }

  div#main, .blog_main, .pagination a:hover, .pagination a:active {
    background-color: white;
    border-color: #108AC6;
  }

  div#main {
    border: 1px solid;
    padding: 5px 12px;
    margin: 3px 0 0 5px;
    overflow: hidden;
    display: inline;
    float: right;
    width: 754px;
  }

  .blog_main, .pagination a:hover, .pagination a:active {
    background-color: white;
    border-color: #108AC6;
  }

  div#content {
    margin-top: 5px;
    width: 100%;
    margin-top: 35px;
    position: relative;
    margin: 0 auto 20px auto;
    padding: 0;
    text-align: left;
  }
</style>
<div id="content">
  <div id="local">
    <div id="blog_owner">
      <div><%= current_user.name.to_s %></div>
    </div>

    <div id="blog_actions">
      <ul>
        <li>浏览: 58449 次</li>
        <li>性别: 男</li>
        <li>来自: 沈阳</li>
      </ul>
    </div>
    <div id="user_visits" class="clearfix">
      <h5>最近访客
      <span style="font-weight:normal;font-size:12px;padding-left:30px;">
        <a href="/blog/user_visits">更多访客&gt;&gt;</a>
      </span>
      </h5>
      <div class="user_visit">
        <div class="left"><a href="http://qq1264926943.iteye.com" target="_blank" title="qq1264926943">qq1264926943</a>
        </div>
      </div>
      <div class="user_visit">
        <div class="left"><a href="http://guoxun.iteye.com" target="_blank" title="guoxun">guoxun</a></div>
      </div>
    </div>

    <div id="blog_menu">
      <h5>文章分类</h5>
      <ul>
        <li><a href="/">全部博客 (126)</a></li>
        <li><a href="/category/185738">DOS (1)</a></li>
      </ul>
    </div>
  </div>
  <div id="main">
    <div class="blog_main">
      <div>
        <h3><%= link_to @article.title, @article %></h3>
      </div>
      <div><%= @article.text %></div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<style>
  .header_link {
    padding-right: 40px;
    float: right;
  }
  .header {
    height: 62px;
    width: 100%;
    overflow: hidden;
    zoom: 1;
    border-bottom: 1px solid #d6dfea;
    background: #eff4fa;
  }
</style>
<div class="header">
  <div class="header_link">
    <%= link_to '首页', root_path %>&nbsp;|&nbsp;
    <%= link_to '个人信息', current_user %>&nbsp;|&nbsp;
    <% if current_user.present? %>
        <%= link_to '退出', logout_path %>
    <% else %>
        <%= link_to '登录', login_path  %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
  <!--<title>Blog</title>-->
  <!--< %= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>-->
  <!--< %= javascript_include_tag 'application', 'data-turbolinks-track' => true %>-->
  <!--< %= csrf_meta_tags %>-->
<!--</head>-->
<!--<body>-->

<!--< %= yield %>-->

<!--</body>-->
<!--</html>-->



<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
  <title>博客系统</title>
  <META content="text/html; charset=utf-8" http-equiv="Content-Type">
  <meta name="renderer" content="webkit|ie-stand|ie-comp">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <script type="text/javascript" src="/jquery-1.5.2.min.js"></script>
  <script type="text/javascript" src="/jquery-ui-1.8.12.custom.min.js"></script>
  <link rel="stylesheet" href="/jquery-ui-1.8.12.custom.css" type="text/css" media="screen, projection">
  <link rel="stylesheet" type="text/css" href="/application.css"/>
  <%= yield(:head) %>
</HEAD>
<BODY>
<%= render :partial => "layouts/header" -%>
<%= yield -%>
</BODY>
</HTML>

app/views/user/login.html.erb
<%= form_for @user, url: {action: 'login_to'} do |f| %>
    用户名:<%= f.text_field :name %><br/>
    密码:<%= f.text_field :password %><br/>
    <%= f.submit "登录" %>
<% end %>

app/views/user/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
    用户名:<%= f.text_field :name %><br/>
    密码:<%= f.text_field :password %><br/>
    邮箱:<%= f.text_field :email %><br/>
    电话:<%= f.text_field :mobile %><br/>
    <%= f.submit "提交" %>
<% end %>

app/views/user/show.html.erb
<%= @user.name %><br/>
<%= @user.mobile %><br/>
<%= session[:user_id] %>
<%= current_user.id %>

app/views/welcome/_search.html.erb
<style>
  #local {
    float: right;
    width: 220px;
    display: inline;
    margin-top: 5px;
  }
  #local div{
    border: 1px solid #A8BACD;
    margin-bottom: 5px;
    background-color: #fafafa;
    padding: 1px;
  }
</style>
<div id="local">
  <div>
    <%= form_for :articles, url: '/articles/search', method: :get do |f| %>
        <%= f.text_field :title, :size => "15", :style => "width: 135px;" , placeholder: "输入相关内容" %>
        <%= f.submit "搜索", :style => "width: 68px;" %>
    <% end -%>
  </div>

  <div>
    <h3>热门文章</h3>
    <ul>
      <% latest_articles.each do |article| %>
          <li><%= link_to article.title.to_s, article %></li>
      <% end %>
    </ul>
  </div>
  <div>
    <h3>相关文章</h3>
    <ul>
      <% latest_articles.each do |article| %>
          <li><%= link_to article.title.to_s, article %></li>
      <% end %>
    </ul>
  </div>
  <div>
    <h3>一周排行</h3>
    <ul>
      <% latest_articles.each do |article| %>
          <li><%= link_to article.title.to_s, article %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/welcome/index.html.erb
<style>
  .news {
    float: left;
    width: 720px;
    display: inline;
    margin-top: 5px;
    overflow: hidden;
  }
</style>
<div class="main">
  <div class="news"></div>
  <%= render 'welcome/search' %>
</div>